/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class Personalizar extends javax.swing.JFrame {

    /**
     * Creates new form Personalizar
     */
    public Personalizar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
        //Objeto del MenuPrincipal
    MenuPrincipal aux = new MenuPrincipal();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt = new javax.swing.JLabel();
        Txt2 = new javax.swing.JLabel();
        Txt3 = new javax.swing.JLabel();
        Alto = new javax.swing.JSpinner();
        Ancho = new javax.swing.JSpinner();
        Nminas = new javax.swing.JSpinner();
        Cancelar = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 165));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt.setText("Alto");
        getContentPane().add(Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt2.setText("Ancho");
        getContentPane().add(Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Txt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt3.setText("Minas");
        getContentPane().add(Txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Alto.setModel(new javax.swing.SpinnerNumberModel(2, 2, 30, 1));
        getContentPane().add(Alto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 60, -1));

        Ancho.setModel(new javax.swing.SpinnerNumberModel(2, 2, 30, 1));
        getContentPane().add(Ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));

        Nminas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(Nminas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, -1));

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 30));

        Confirmar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Confirmar.setText("Continuar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        
        int a = 1,b = 0,c = 1,d;
        try{
            a = Integer.parseInt(Alto.getModel().getValue().toString());
            b = Integer.parseInt(Ancho.getModel().getValue().toString());
            c = Integer.parseInt(Nminas.getModel().getValue().toString());
        }catch(NumberFormatException e){ //Capturar Excepción de Error en el formato del número
            System.out.println("Excepción "+e+" capturada");
        }if( a==b && c < a*b){
                d = (c*100)/(a*b);
                aux.colocar(a,b,c,d);
                this.setVisible(false);
        }else if(a!=b){
            JOptionPane.showMessageDialog(null, "ERROR!!! El Alto y Ancho deben ser IGUALES");
        }else{
            JOptionPane.showMessageDialog(null, "ERROR!!! Hay MÁS minas que casillas");
        }
            
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Alto;
    private javax.swing.JSpinner Ancho;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JSpinner Nminas;
    private javax.swing.JLabel Txt;
    private javax.swing.JLabel Txt2;
    private javax.swing.JLabel Txt3;
    // End of variables declaration//GEN-END:variables
}
